---
- name: Apparmor sssd
  ansible.builtin.template:
    src: sssd_apparmor.j2
    dest: /etc/apparmor.d/usr.sbin.sssd
    owner: root
    group: root
    mode: 0644
  notify: Restart apparmor
  tags: ad_session_sssd_add

- name: Copy sssd.conf
  ansible.builtin.template:
    src: sssd.conf.j2
    dest: /etc/sssd/sssd.conf
    owner: root
    group: root
    mode: 0600
  notify: Restart SSSD
  tags: ad_session_sssd_add

- name: Copy pam common-session
  ansible.builtin.template:
    src: common-session.j2
    dest: /etc/pam.d/common-session
    owner: root
    group: root
    mode: 0644
  when: ad_replace_sss_conf
  tags: ad_session_pam_add

- name: Configure pam common-session
  ansible.builtin.lineinfile:
    path: /etc/pam.d/common-session
    line: "session required        pam_mkhomedir.so skel=/etc/skel/ umask=0022"
  tags: ad_session_pam_add

- name: Enable SSSD
  ansible.builtin.systemd:
    name: sssd
    enabled: true
    state: started
  tags: ad_session_sssd_start
